Update publishing warnings
ministryofjustice/fb-editor pull request #1866
Opened 2022-11-04 15:05 UTC by H3ll3m4

## Context
Publishing warnings are being updated. Some of the content has to be changed but also the display of autocomplete warnings with the other warnings.

## Implementation
In order to change the content it is a simple update of the translation file en.yml. In order to have the publishing warnings for autocomplete uniform with the rest, we add the publish them in the list if presenters for the publishing page presenter and remove them from the publish environment view.

## Tests
Unit tests and publishing acceptance tests have been updated. Local testing with manual observation performed.

2022-11-09 17:41 UTC, njseeto reviewed
Looks great, just a couple of suggestions.

2022-11-09 17:41 UTC, njseeto commented on app/presenters/autocomplete_items_presenter.rb
>    def messages
```suggestion
  def message
```

Are we able to rename this method to `message` and then delete the new `message` method?

2022-11-09 17:41 UTC, njseeto commented on app/presenters/autocomplete_items_presenter.rb
> +        link = govuk_link_to(component.humanised_title, Rails.application.routes.url_helpers.edit_page_path(service.service_id, page.uuid))
```suggestion

```
could we move this method to a private method? Then we can just call it in the `description` variable. Something like:

```
  def messages
    pages_with_autocomplete_component.each_with_object([]) do |page, arry|
      page.components.each do |component|
        next unless component.uuid.in?(component_uuids_without_items)

        description = I18n.t(
          "publish.autocomplete_items.#{deployment_environment}.message",
          title: link(component, page)
        )

        msg = description.html_safe
        arry.push(msg)
      end
    end
  end

  private

  def link(component, page)
    govuk_link_to(
      component.humanised_title,
      Rails.application.routes.url_helpers.edit_page_path(service.service_id, page.uuid)
    )
  end
```

2022-11-09 17:41 UTC, njseeto commented on app/presenters/autocomplete_items_presenter.rb
> +        description = I18n.t("publish.autocomplete_items.#{deployment_environment}.message", title: link)
```suggestion
        msg = I18n.t(
          "publish.autocomplete_items.#{deployment_environment}.message",
          title: link
        ).html_safe
```
Not a biggie, but we could chain the `html_safe` in the variable assignment and rename the variable, then we can delete the `msg = description.html_safe` line.

2022-11-09 17:41 UTC, njseeto commented on spec/presenters/publishing_page_presenter_spec.rb
> +         from_address_presenter]
```suggestion
        [
          submission_pages_presenter,
          autocomplete_warning,
          from_address_presenter
        ]
```

Small formatting suggestion

2022-11-10 15:56 UTC, brenetic commented on app/presenters/publishing_page_presenter.rb
> +    return presenters if deployment_environment == 'dev'
why do we not want the autocomplete presenter to be there if it's dev?

2022-11-10 16:10 UTC, brenetic commented
can we have a screenshot please?

i may have completely misunderstood the story, but are the autocomplete warnings now part of the list of _all_ publishing warnings on the publishing page? if that's the case then maintaining the `autocomplete_warning` partial might not be necessary as the `SubmissionWarningsPresenter` will just map over any presenters that it's initialized with and spit out the messages

2022-11-10 16:52 UTC, H3ll3m4 commented
We moved the autocomplete warning in the first header group only for publishing to Live. However, as it has been clarified this morning after the stand up, we want the publishing to Test to have autocomplete warnings separated, so like before we started the work on this feature. The results looks like this, with a server running locally : 
<img width="756" alt="Screenshot 2022-11-10 at 16 44 08" src="https://user-images.githubusercontent.com/26165112/201156032-11778d57-2bf3-42d9-9cd4-6e024ae20bd0.png">

In addition, we added a few updates of the content, following version 1.3 of the [publishing warnings](https://docs.google.com/spreadsheets/d/11FvkKJcO1Yfn3bVOM9IPSD0_LHjqgTSJmASx33lYe-E/edit#gid=814462722), see tab 1.3, and only the text written ToDo on column K.

2022-11-10 18:17 UTC, brenetic requested changes

2022-11-10 18:17 UTC, brenetic commented on app/views/publish/_autocomplete_warning.html.erb
> +<% autocomplete_warning.message.each do |message| %>
is there only one message now per presenter? if so do we need to loop? if not we could keep both methods

2022-11-11 11:35 UTC, brenetic commented on app/presenters/autocomplete_items_presenter.rb
> +  end
`alias :message, :messages`

2022-11-14 12:32 UTC, brenetic approved these changes
🚀

2022-11-14 12:33 UTC, merged