Fix logic around display of autocomplete warnings
ministryofjustice/fb-editor pull request #1910
Opened 2022-11-25 10:23 UTC by chrispymm

Fixes some logic around the publishing warnings and how we handle autocomplete issues.

The problem was that both in dev and live, the autocomplete warnings only showed if 'collect information by email' was off.  

In dev the solution is pretty easy, as we can show both of the top-level warnings at the same time.

In live the autocomplete warnings are part of the 'submission warnings' block.

So we need to ensure the submission warnings includes the right warnings (i.e. no from address warnings when collect info by email is off), and gets shown if there are any autocomplete issues.

**Before:**
![image](https://user-images.githubusercontent.com/595564/203961175-54e252c3-28bb-454b-bf81-7f8cf5ad4647.png)
Form has an autocomplete without any options, but the user wouldn't know

**After:**
![image](https://user-images.githubusercontent.com/595564/203961877-53187fc2-5633-4bf7-9cf5-cc2158b825c0.png)
Email warning and autocomplete warnings show, but there are no 'From address' warnings in live due to 'collect info by email' being off

2022-11-25 12:28 UTC, njseeto requested changes
looks good, just one small question

2022-11-25 12:28 UTC, njseeto commented on app/presenters/service_output_warning_presenter.rb
> +  def blank?
could we use ruby's in built `blank?` method rather than defining our own?

2022-11-30 12:14 UTC, brenetic approved these changes
🚀

2022-11-30 12:16 UTC, njseeto approved these changes
🚀

2022-11-30 13:47 UTC, merged